. ~/bin/dotfiles/bash/sections/env
. ~/bin/dotfiles/bash/sections/config
. ~/bin/dotfiles/bash/sections/aliases
. ~/bin/dotfiles/bash/sections/custom


PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
